//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flats
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string ComplexName { get; set; }
        public string Address { get; set; }
        public Nullable<int> NumberFlat { get; set; }
        public Nullable<System.DateTime> BuyDate { get; set; }
        public Nullable<int> PhotoId { get; set; }
        public string Status { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
