//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        public int Id { get; set; }
        public int FlatId { get; set; }
        public byte[] ImageData { get; set; }
        public int ImageStatusId { get; set; }
        public System.DateTime CreatedData { get; set; }
    
        public virtual Flats FlatList { get; set; }
        public virtual ImageStatus ImageStatus { get; set; }
    }
}
